site:
  title: 'SUSE® Rancher Prime: Observability'
  start_page: next@observability:en:classic.adoc

content:
  sources:
    - url: ./
      branches: [main]
      start_paths: [shared, docs/next, docs/version-*]

ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher

asciidoc:
  attributes:
    ss-build-type: 'product' # 'community' or 'product'
    ss-rancher-product-name: 'SUSE® Rancher Prime: Observability'
    ss-community-product-name: 'StackState'
    page-pagination: ''
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: build/site
